services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres_test
      - POSTGRES_PASSWORD=postgres_test
      - POSTGRES_DB=waitlist_test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_test -d waitlist_test"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 5s
      retries: 5

  migrations:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.test
    environment:
      - DB_HOST=db
    command: sh -c "npx knex migrate:latest"

  app:
    build:
      context: .
      args:
        NODE_ENV: test
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.test
    environment:
      - NODE_ENV=test
      - DB_HOST=db
      - REDIS_HOST=redis
    command: npm run dev
    volumes:
      - ./:/usr/local/app
    depends_on:
      migrations:
        condition: service_started
      redis:
        condition: service_healthy
